[2025-04-23T19:13:59.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T19:13:59.882+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.load_to_snowflake scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T19:13:59.887+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_etl_dbt_pipeline.load_to_snowflake scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T19:13:59.888+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-23T19:13:59.896+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_to_snowflake> on 2025-04-22 00:00:00+00:00
[2025-04-23T19:13:59.905+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'full_etl_dbt_pipeline', 'load_to_snowflake', 'scheduled__2025-04-22T00:00:00+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt_pipeline.py', '--cfg-path', '/tmp/tmprlu2ryd1']
[2025-04-23T19:13:59.908+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1414) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T19:13:59.908+0000] {standard_task_runner.py:105} INFO - Job 239: Subtask load_to_snowflake
[2025-04-23T19:13:59.908+0000] {standard_task_runner.py:72} INFO - Started process 1417 to run task
[2025-04-23T19:13:59.948+0000] {task_command.py:467} INFO - Running <TaskInstance: full_etl_dbt_pipeline.load_to_snowflake scheduled__2025-04-22T00:00:00+00:00 [running]> on host aab73994fc52
[2025-04-23T19:14:00.089+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_etl_dbt_pipeline' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T00:00:00+00:00'
[2025-04-23T19:14:00.091+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T19:14:00.106+0000] {connection.py:477} INFO - Snowflake Connector for Python Version: 3.14.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-04-23T19:14:00.107+0000] {connection.py:1400} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-23T19:19:43.261+0000] {logging_mixin.py:190} INFO - Successfully loaded 360 rows into USER_DB_BEETLE.raw.stock_data
[2025-04-23T19:19:43.391+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T19:19:43.408+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T19:19:43.408+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=full_etl_dbt_pipeline, task_id=load_to_snowflake, run_id=scheduled__2025-04-22T00:00:00+00:00, execution_date=20250422T000000, start_date=20250423T191359, end_date=20250423T191943
[2025-04-23T19:19:43.455+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T19:19:43.475+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T19:19:43.477+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
